- name: checking ofr variables
  hosts: localhost
  become: yes
  vars_files:
    - variables.yaml
  vars_prompt:
    - variablesprompt.yaml
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is: {{USERNAME}} , password is: {{PASSWORD}}"
  
