- name: loops
  hosts: web
  become: yes
  tasks:
  - name: list of items
    ansible.builtin.package:
      name: "{{items}}"
      state: present
    loops:
      - git
      - mysql
      - postfix 

