
- name: loops
  hosts: web
  become: yes
  tasks:
    - name: list of loops
      ansible.builtin.package:
        name: "{{items}}"
        state: present
      loops:
        - git
        - mysql
        - postfix 

