- name: loops
  hosts: web
  become: yes
  tasks:
    - name: print persons
      ansible.builtin.package:
          name: "{{item}}"
          state: present
      loops:
          - git
          - mysql
          - postfix 

