- name: checking the variables
  hosts: web
  become: yes
  vars_files:
    - variables.yaml
  vars_prompt:
    - name: enter the user name
      prompt: "{{USERNAME}}"
      private: false
    - name: password
      prompt: "{{PASSWORD}}"
      private: false
  tasks:
    - name: checking the variables
      ansible.builtin.debug:
        msg: "username is {{USERNAME}} , password is {{PASSWORD}}"